import * as core from "@actions/core";
import * as github from "@actions/github";
import Anthropic from "@anthropic-ai/sdk";

async function run(): Promise<void> {
  const anthropicKey = core.getInput("anthropic_api_key", { required: true });
  const githubToken = core.getInput("github_token", { required: true });
  const model = core.getInput("model") || "claude-sonnet-4-6";
  const maxTokens = parseInt(core.getInput("max_tokens") || "2048", 10);

  const context = github.context;
  const octokit = github.getOctokit(githubToken);
  const anthropic = new Anthropic({ apiKey: anthropicKey });

  if (context.eventName === "pull_request") {
    await reviewPullRequest(context, octokit, anthropic, model, maxTokens);
  } else if (context.eventName === "issues" && context.payload.action === "opened") {
    await triageIssue(context, octokit, anthropic, model, maxTokens);
  } else {
    core.info(`Event '${context.eventName}' not handled — skipping.`);
  }
}

async function reviewPullRequest(
  context: typeof github.context,
  octokit: ReturnType<typeof github.getOctokit>,
  anthropic: Anthropic,
  model: string,
  maxTokens: number
): Promise<void> {
  const { owner, repo } = context.repo;
  const pull_number = context.payload.pull_request!.number;

  core.info(`Reviewing PR #${pull_number} in ${owner}/${repo}`);

  // Fetch PR details and diff
  const [prData, filesData] = await Promise.all([
    octokit.rest.pulls.get({ owner, repo, pull_number }),
    octokit.rest.pulls.listFiles({ owner, repo, pull_number, per_page: 100 }),
  ]);

  const pr = prData.data;
  const files = filesData.data;

  const filesSummary = files
    .map((f) => {
      const patch = f.patch ? (f.patch.length > 2000 ? f.patch.slice(0, 2000) + "\n[...truncated]" : f.patch) : "(binary or no diff)";
      return `### ${f.filename} (+${f.additions}/-${f.deletions})\n\`\`\`diff\n${patch}\n\`\`\``;
    })
    .join("\n\n");

  const prompt = `You are a helpful code reviewer. Review the following pull request and provide constructive, concise feedback.

## PR: ${pr.title}

**Author:** ${pr.user?.login}
**Base branch:** ${pr.base.ref} ← **Head branch:** ${pr.head.ref}
**Description:** ${pr.body || "(no description provided)"}
**Changes:** +${pr.additions} additions, -${pr.deletions} deletions across ${pr.changed_files} files

## Changed Files

${filesSummary}

---

Provide a structured review with:
1. **Summary** — what this PR does in 2–3 sentences
2. **Strengths** — what's done well
3. **Suggestions** — specific, actionable improvements (reference file names and line context)
4. **Questions** — anything unclear that the author should clarify
5. **Verdict** — Approve / Request Changes / Comment (with brief reason)

Be constructive and specific. Use Markdown formatting.`;

  const response = await anthropic.messages.create({
    model,
    max_tokens: maxTokens,
    messages: [{ role: "user", content: prompt }],
  });

  const reviewBody = response.content[0].type === "text" ? response.content[0].text : "";
  const reviewBodyWithFooter = `${reviewBody}\n\n---\n*🤖 Review generated by [github-claude-mcp](https://github.com/mohit1jindal/github-claude-mcp) using ${model}*`;

  await octokit.rest.pulls.createReview({
    owner,
    repo,
    pull_number,
    body: reviewBodyWithFooter,
    event: "COMMENT",
  });

  core.info(`Posted review on PR #${pull_number}`);
}

async function triageIssue(
  context: typeof github.context,
  octokit: ReturnType<typeof github.getOctokit>,
  anthropic: Anthropic,
  model: string,
  maxTokens: number
): Promise<void> {
  const { owner, repo } = context.repo;
  const issue = context.payload.issue!;

  core.info(`Triaging issue #${issue.number} in ${owner}/${repo}`);

  // Fetch available labels for this repo
  const { data: availableLabels } = await octokit.rest.issues.listLabelsForRepo({ owner, repo });
  const labelNames = availableLabels.map((l) => l.name).join(", ");

  const prompt = `You are a helpful assistant that triages GitHub issues.

## Issue #${issue.number}: ${issue.title}

**Author:** ${issue.user?.login}
**Body:**
${issue.body || "(no body provided)"}

## Available labels in this repo:
${labelNames || "(none)"}

Respond with a JSON object (no markdown, pure JSON) in this exact format:
{
  "comment": "A helpful 2–3 sentence triage comment to post on the issue",
  "suggested_labels": ["label1", "label2"],
  "priority": "high | medium | low",
  "type": "bug | feature | question | documentation | other"
}

Only suggest labels that exist in the available labels list. Keep the comment friendly and welcoming.`;

  const response = await anthropic.messages.create({
    model,
    max_tokens: maxTokens,
    messages: [{ role: "user", content: prompt }],
  });

  let triage: { comment: string; suggested_labels: string[]; priority: string; type: string };
  try {
    const text = response.content[0].type === "text" ? response.content[0].text : "{}";
    triage = JSON.parse(text);
  } catch {
    core.warning("Could not parse triage JSON — posting raw comment");
    triage = {
      comment: response.content[0].type === "text" ? response.content[0].text : "Thank you for filing this issue!",
      suggested_labels: [],
      priority: "medium",
      type: "other",
    };
  }

  // Post the triage comment
  await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: issue.number,
    body: `${triage.comment}\n\n*🤖 Auto-triage by [github-claude-mcp](https://github.com/mohit1jindal/github-claude-mcp) — Priority: **${triage.priority}** | Type: **${triage.type}***`,
  });

  // Apply suggested labels if they exist
  const validLabels = triage.suggested_labels.filter((l) => availableLabels.some((al) => al.name === l));
  if (validLabels.length > 0) {
    await octokit.rest.issues.addLabels({ owner, repo, issue_number: issue.number, labels: validLabels });
    core.info(`Applied labels: ${validLabels.join(", ")}`);
  }

  core.info(`Triaged issue #${issue.number}`);
}

run().catch((err) => {
  core.setFailed(err.message);
});
